# Generated by Django 3.1.5 on 2021-01-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogBody', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tittle',
            new_name='title',
        ),
    ]
